"""add meeting_uploads table

Revision ID: 1ba39d0debaa
Revises: 94a4211b3e6a
Create Date: 2026-09-23 11:14:43.096056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba39d0debaa'
down_revision: Union[str, Sequence[str], None] = '94a4211b3e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('AUDIO', 'VIDEO', 'TRANSCRIPT_FILE', 'TRANSCRIPT_TEXT', name='uploadkind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='uploadstatus'), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['feedback_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_uploads')
    # ### end Alembic commands ###
