"""add author_id to discussion_notes and decisions, owner_id to action_items

Revision ID: 94a4211b3e6a
Revises: 9842a6b70709
Create Date: 2026-09-22 19:47:56.450118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a4211b3e6a'
down_revision: Union[str, Sequence[str], None] = '9842a6b70709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_discussion_notes_author_id_users', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_decisions_author_id_users', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_action_items_owner_id_users', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_action_items_owner_id_users', type_='foreignkey')
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_decisions_author_id_users', type_='foreignkey')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('discussion_notes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussion_notes_author_id_users', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
