"""add discussion_status to clusters

Revision ID: 9842a6b70709
Revises: d0b984981d55
Create Date: 2026-09-22 19:28:15.116524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9842a6b70709'
down_revision: Union[str, Sequence[str], None] = 'd0b984981d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'discussion_status',
                sa.Enum('PENDING', 'DISCUSSED', 'SKIPPED', 'DEFERRED', name='discussionstatus'),
                nullable=False,
                server_default='PENDING',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_column('discussion_status')

    # ### end Alembic commands ###
