"""add participant_id to votes

Revision ID: c496825e7217
Revises: cda190f63753
Create Date: 2026-09-22 18:59:38.632044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c496825e7217'
down_revision: Union[str, Sequence[str], None] = 'cda190f63753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_votes_participant_id_users', 'users', ['participant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_votes_participant_id_users', type_='foreignkey')
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
