"""add author_id to feedback_cards

Revision ID: cda190f63753
Revises: 8489561c7db3
Create Date: 2026-09-22 17:50:56.492678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda190f63753'
down_revision: Union[str, Sequence[str], None] = '8489561c7db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_feedback_cards_author_id_users', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_cards_author_id_users', type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
