"""add voting_closed to feedback_cycles

Revision ID: d0b984981d55
Revises: c496825e7217
Create Date: 2026-09-22 19:13:24.784537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b984981d55'
down_revision: Union[str, Sequence[str], None] = 'c496825e7217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voting_closed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_cycles', schema=None) as batch_op:
        batch_op.drop_column('voting_closed')

    # ### end Alembic commands ###
