"""add summary_confirmed to feedback_cycles

Revision ID: e8b28255e42e
Revises: 115567cd4353
Create Date: 2026-09-23 11:25:52.761726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b28255e42e'
down_revision: Union[str, Sequence[str], None] = '115567cd4353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_confirmed', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_cycles', schema=None) as batch_op:
        batch_op.drop_column('summary_confirmed')

    # ### end Alembic commands ###
